# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Estimativa de CO2 no mundom
email: leandroresendemundim@gmail.com
baseurl: ""
url: "http://leandromundim.com.br"
github_username:  drmundim

# Build settings
markdown: kramdown
permalink: /:title/
